// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: protobuf/FishingValley.proto

package FishingValleyProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 验证登录信息 1
type ConfirmLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` //由登录服务器传递的登录凭证
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmLogin) Reset() {
	*x = ConfirmLogin{}
	mi := &file_protobuf_FishingValley_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmLogin) ProtoMessage() {}

func (x *ConfirmLogin) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_FishingValley_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmLogin.ProtoReflect.Descriptor instead.
func (*ConfirmLogin) Descriptor() ([]byte, []int) {
	return file_protobuf_FishingValley_proto_rawDescGZIP(), []int{0}
}

func (x *ConfirmLogin) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// 验证登录信息的回复 1
type ConfirmLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Id            uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmLoginResponse) Reset() {
	*x = ConfirmLoginResponse{}
	mi := &file_protobuf_FishingValley_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmLoginResponse) ProtoMessage() {}

func (x *ConfirmLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_FishingValley_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmLoginResponse.ProtoReflect.Descriptor instead.
func (*ConfirmLoginResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_FishingValley_proto_rawDescGZIP(), []int{1}
}

func (x *ConfirmLoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmLoginResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConfirmLoginResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 客户端准备完毕 2
type UserReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReady) Reset() {
	*x = UserReady{}
	mi := &file_protobuf_FishingValley_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReady) ProtoMessage() {}

func (x *UserReady) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_FishingValley_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReady.ProtoReflect.Descriptor instead.
func (*UserReady) Descriptor() ([]byte, []int) {
	return file_protobuf_FishingValley_proto_rawDescGZIP(), []int{2}
}

// 用户移动 3
type Movement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movement) Reset() {
	*x = Movement{}
	mi := &file_protobuf_FishingValley_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movement) ProtoMessage() {}

func (x *Movement) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_FishingValley_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movement.ProtoReflect.Descriptor instead.
func (*Movement) Descriptor() ([]byte, []int) {
	return file_protobuf_FishingValley_proto_rawDescGZIP(), []int{3}
}

func (x *Movement) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Movement) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Movement) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_protobuf_FishingValley_proto protoreflect.FileDescriptor

const file_protobuf_FishingValley_proto_rawDesc = "" +
	"\n" +
	"\x1cprotobuf/FishingValley.proto\" \n" +
	"\fConfirmLogin\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"Z\n" +
	"\x14ConfirmLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\v\n" +
	"\tUserReady\"8\n" +
	"\bMovement\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01yB\x15Z\x13/FishingValleyProtob\x06proto3"

var (
	file_protobuf_FishingValley_proto_rawDescOnce sync.Once
	file_protobuf_FishingValley_proto_rawDescData []byte
)

func file_protobuf_FishingValley_proto_rawDescGZIP() []byte {
	file_protobuf_FishingValley_proto_rawDescOnce.Do(func() {
		file_protobuf_FishingValley_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_FishingValley_proto_rawDesc), len(file_protobuf_FishingValley_proto_rawDesc)))
	})
	return file_protobuf_FishingValley_proto_rawDescData
}

var file_protobuf_FishingValley_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuf_FishingValley_proto_goTypes = []any{
	(*ConfirmLogin)(nil),         // 0: ConfirmLogin
	(*ConfirmLoginResponse)(nil), // 1: ConfirmLoginResponse
	(*UserReady)(nil),            // 2: UserReady
	(*Movement)(nil),             // 3: Movement
}
var file_protobuf_FishingValley_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_FishingValley_proto_init() }
func file_protobuf_FishingValley_proto_init() {
	if File_protobuf_FishingValley_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_FishingValley_proto_rawDesc), len(file_protobuf_FishingValley_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_FishingValley_proto_goTypes,
		DependencyIndexes: file_protobuf_FishingValley_proto_depIdxs,
		MessageInfos:      file_protobuf_FishingValley_proto_msgTypes,
	}.Build()
	File_protobuf_FishingValley_proto = out.File
	file_protobuf_FishingValley_proto_goTypes = nil
	file_protobuf_FishingValley_proto_depIdxs = nil
}
