// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: protobuf/FishingValley.proto

package FishingValleyProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 验证登录信息 1
type ConfirmLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` //由登录服务器传递的登录凭证
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmLogin) Reset() {
	*x = ConfirmLogin{}
	mi := &file_protobuf_FishingValley_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmLogin) ProtoMessage() {}

func (x *ConfirmLogin) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_FishingValley_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmLogin.ProtoReflect.Descriptor instead.
func (*ConfirmLogin) Descriptor() ([]byte, []int) {
	return file_protobuf_FishingValley_proto_rawDescGZIP(), []int{0}
}

func (x *ConfirmLogin) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// 验证登录信息的回复 1
type ConfirmLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Id            uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmLoginResponse) Reset() {
	*x = ConfirmLoginResponse{}
	mi := &file_protobuf_FishingValley_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmLoginResponse) ProtoMessage() {}

func (x *ConfirmLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_FishingValley_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmLoginResponse.ProtoReflect.Descriptor instead.
func (*ConfirmLoginResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_FishingValley_proto_rawDescGZIP(), []int{1}
}

func (x *ConfirmLoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmLoginResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConfirmLoginResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 客户端准备完毕 2
type UserReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReady) Reset() {
	*x = UserReady{}
	mi := &file_protobuf_FishingValley_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReady) ProtoMessage() {}

func (x *UserReady) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_FishingValley_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReady.ProtoReflect.Descriptor instead.
func (*UserReady) Descriptor() ([]byte, []int) {
	return file_protobuf_FishingValley_proto_rawDescGZIP(), []int{2}
}

// 用户移动 3
type Movement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Direction     bool                   `protobuf:"varint,4,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movement) Reset() {
	*x = Movement{}
	mi := &file_protobuf_FishingValley_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movement) ProtoMessage() {}

func (x *Movement) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_FishingValley_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movement.ProtoReflect.Descriptor instead.
func (*Movement) Descriptor() ([]byte, []int) {
	return file_protobuf_FishingValley_proto_rawDescGZIP(), []int{3}
}

func (x *Movement) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Movement) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Movement) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Movement) GetDirection() bool {
	if x != nil {
		return x.Direction
	}
	return false
}

// 用户离开游戏 4
type PlayerLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeave) Reset() {
	*x = PlayerLeave{}
	mi := &file_protobuf_FishingValley_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeave) ProtoMessage() {}

func (x *PlayerLeave) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_FishingValley_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeave.ProtoReflect.Descriptor instead.
func (*PlayerLeave) Descriptor() ([]byte, []int) {
	return file_protobuf_FishingValley_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerLeave) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

// 玩家区块改变 5
type PlayerChunkChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkX        uint32                 `protobuf:"varint,1,opt,name=chunk_x,json=chunkX,proto3" json:"chunk_x,omitempty"`
	ChunkY        uint32                 `protobuf:"varint,2,opt,name=chunk_y,json=chunkY,proto3" json:"chunk_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerChunkChange) Reset() {
	*x = PlayerChunkChange{}
	mi := &file_protobuf_FishingValley_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerChunkChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerChunkChange) ProtoMessage() {}

func (x *PlayerChunkChange) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_FishingValley_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerChunkChange.ProtoReflect.Descriptor instead.
func (*PlayerChunkChange) Descriptor() ([]byte, []int) {
	return file_protobuf_FishingValley_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerChunkChange) GetChunkX() uint32 {
	if x != nil {
		return x.ChunkX
	}
	return 0
}

func (x *PlayerChunkChange) GetChunkY() uint32 {
	if x != nil {
		return x.ChunkY
	}
	return 0
}

// 玩家区块改变的回应，向周围的区块的玩家发送区块改变的消息 5
type PlayerChunkChangeRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ChunkX        uint32                 `protobuf:"varint,2,opt,name=chunk_x,json=chunkX,proto3" json:"chunk_x,omitempty"`
	ChunkY        uint32                 `protobuf:"varint,3,opt,name=chunk_y,json=chunkY,proto3" json:"chunk_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerChunkChangeRsp) Reset() {
	*x = PlayerChunkChangeRsp{}
	mi := &file_protobuf_FishingValley_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerChunkChangeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerChunkChangeRsp) ProtoMessage() {}

func (x *PlayerChunkChangeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_FishingValley_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerChunkChangeRsp.ProtoReflect.Descriptor instead.
func (*PlayerChunkChangeRsp) Descriptor() ([]byte, []int) {
	return file_protobuf_FishingValley_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerChunkChangeRsp) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerChunkChangeRsp) GetChunkX() uint32 {
	if x != nil {
		return x.ChunkX
	}
	return 0
}

func (x *PlayerChunkChangeRsp) GetChunkY() uint32 {
	if x != nil {
		return x.ChunkY
	}
	return 0
}

// 服务器传送玩家(用于传送等) 6
type TransmitPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AreaId        uint32                 `protobuf:"varint,1,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"` // 传送的区域id
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransmitPlayer) Reset() {
	*x = TransmitPlayer{}
	mi := &file_protobuf_FishingValley_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransmitPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransmitPlayer) ProtoMessage() {}

func (x *TransmitPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_FishingValley_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransmitPlayer.ProtoReflect.Descriptor instead.
func (*TransmitPlayer) Descriptor() ([]byte, []int) {
	return file_protobuf_FishingValley_proto_rawDescGZIP(), []int{7}
}

func (x *TransmitPlayer) GetAreaId() uint32 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

func (x *TransmitPlayer) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TransmitPlayer) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// 发送一个信息 7
type Speak struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Speak) Reset() {
	*x = Speak{}
	mi := &file_protobuf_FishingValley_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Speak) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Speak) ProtoMessage() {}

func (x *Speak) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_FishingValley_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Speak.ProtoReflect.Descriptor instead.
func (*Speak) Descriptor() ([]byte, []int) {
	return file_protobuf_FishingValley_proto_rawDescGZIP(), []int{8}
}

func (x *Speak) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Speak) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 当玩家的状态改变 8
type PlayerStateChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Action        uint32                 `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerStateChange) Reset() {
	*x = PlayerStateChange{}
	mi := &file_protobuf_FishingValley_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStateChange) ProtoMessage() {}

func (x *PlayerStateChange) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_FishingValley_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStateChange.ProtoReflect.Descriptor instead.
func (*PlayerStateChange) Descriptor() ([]byte, []int) {
	return file_protobuf_FishingValley_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerStateChange) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerStateChange) GetAction() uint32 {
	if x != nil {
		return x.Action
	}
	return 0
}

// 信息请求
// 请求一个用户的信息 10
type PlayerInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfoReq) Reset() {
	*x = PlayerInfoReq{}
	mi := &file_protobuf_FishingValley_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfoReq) ProtoMessage() {}

func (x *PlayerInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_FishingValley_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfoReq.ProtoReflect.Descriptor instead.
func (*PlayerInfoReq) Descriptor() ([]byte, []int) {
	return file_protobuf_FishingValley_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerInfoReq) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

// 请求用户信息的回应 10
type PlayerInfoRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	State         uint32                 `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Direction     bool                   `protobuf:"varint,4,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfoRsp) Reset() {
	*x = PlayerInfoRsp{}
	mi := &file_protobuf_FishingValley_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfoRsp) ProtoMessage() {}

func (x *PlayerInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_FishingValley_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfoRsp.ProtoReflect.Descriptor instead.
func (*PlayerInfoRsp) Descriptor() ([]byte, []int) {
	return file_protobuf_FishingValley_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerInfoRsp) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerInfoRsp) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *PlayerInfoRsp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerInfoRsp) GetDirection() bool {
	if x != nil {
		return x.Direction
	}
	return false
}

var File_protobuf_FishingValley_proto protoreflect.FileDescriptor

const file_protobuf_FishingValley_proto_rawDesc = "" +
	"\n" +
	"\x1cprotobuf/FishingValley.proto\" \n" +
	"\fConfirmLogin\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"Z\n" +
	"\x14ConfirmLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\v\n" +
	"\tUserReady\"V\n" +
	"\bMovement\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\bR\tdirection\"\x1f\n" +
	"\vPlayerLeave\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\"E\n" +
	"\x11PlayerChunkChange\x12\x17\n" +
	"\achunk_x\x18\x01 \x01(\rR\x06chunkX\x12\x17\n" +
	"\achunk_y\x18\x02 \x01(\rR\x06chunkY\"Z\n" +
	"\x14PlayerChunkChangeRsp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x17\n" +
	"\achunk_x\x18\x02 \x01(\rR\x06chunkX\x12\x17\n" +
	"\achunk_y\x18\x03 \x01(\rR\x06chunkY\"E\n" +
	"\x0eTransmitPlayer\x12\x17\n" +
	"\aarea_id\x18\x01 \x01(\rR\x06areaId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"6\n" +
	"\x05Speak\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"=\n" +
	"\x11PlayerStateChange\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x16\n" +
	"\x06action\x18\x02 \x01(\rR\x06action\"!\n" +
	"\rPlayerInfoReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\"i\n" +
	"\rPlayerInfoRsp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x14\n" +
	"\x05state\x18\x02 \x01(\rR\x05state\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\bR\tdirectionB\x15Z\x13/FishingValleyProtob\x06proto3"

var (
	file_protobuf_FishingValley_proto_rawDescOnce sync.Once
	file_protobuf_FishingValley_proto_rawDescData []byte
)

func file_protobuf_FishingValley_proto_rawDescGZIP() []byte {
	file_protobuf_FishingValley_proto_rawDescOnce.Do(func() {
		file_protobuf_FishingValley_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_FishingValley_proto_rawDesc), len(file_protobuf_FishingValley_proto_rawDesc)))
	})
	return file_protobuf_FishingValley_proto_rawDescData
}

var file_protobuf_FishingValley_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_protobuf_FishingValley_proto_goTypes = []any{
	(*ConfirmLogin)(nil),         // 0: ConfirmLogin
	(*ConfirmLoginResponse)(nil), // 1: ConfirmLoginResponse
	(*UserReady)(nil),            // 2: UserReady
	(*Movement)(nil),             // 3: Movement
	(*PlayerLeave)(nil),          // 4: PlayerLeave
	(*PlayerChunkChange)(nil),    // 5: PlayerChunkChange
	(*PlayerChunkChangeRsp)(nil), // 6: PlayerChunkChangeRsp
	(*TransmitPlayer)(nil),       // 7: TransmitPlayer
	(*Speak)(nil),                // 8: Speak
	(*PlayerStateChange)(nil),    // 9: PlayerStateChange
	(*PlayerInfoReq)(nil),        // 10: PlayerInfoReq
	(*PlayerInfoRsp)(nil),        // 11: PlayerInfoRsp
}
var file_protobuf_FishingValley_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_FishingValley_proto_init() }
func file_protobuf_FishingValley_proto_init() {
	if File_protobuf_FishingValley_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_FishingValley_proto_rawDesc), len(file_protobuf_FishingValley_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_FishingValley_proto_goTypes,
		DependencyIndexes: file_protobuf_FishingValley_proto_depIdxs,
		MessageInfos:      file_protobuf_FishingValley_proto_msgTypes,
	}.Build()
	File_protobuf_FishingValley_proto = out.File
	file_protobuf_FishingValley_proto_goTypes = nil
	file_protobuf_FishingValley_proto_depIdxs = nil
}
